### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tamdbho** [Ike-Sanderson/Demultiplex#3]
Great work Ike! I only have some minor tweaks
1)
```
Open 4 files as rt 
    Read and strip header line
    Read and strip sequence line
    Read and strip plus line
    Read and strip quality score line
```
Remember to store all these in separate variables so that if you can call on it later

2. 
```
    If R2 sequence/index has N base 
        call function: write to unknown file 
        increase unknown counter
    If R3 sequence/index has N base 
        call function: write to unknown file 
        increase unknown counter
```
The unknown files will contain reads with indexes that are either low in quality or unknown. How do you test for unknown? My suggestion is to store all the expected index (from txt file on shared folder) in some variable and refer to it to test if the R2/R3 sequence like is a known index or not. 

3. 
```
             Check quality scores - if R1 mean quality score <= 30 #more lenient for read Q score
                  call function: write to unknown file
                  increase unknown counter
             Check quality scores - if R1 mean quality score <= 30 #more lenient for read Q score
                  call function: write to unknown file
                  increase unknown counter
```
I think for the second condition you meant "R4"
This is a great tip! I missed this detail in my own script. I only checked my R2/R3 sequence if there is a "N" or not to judge quality score.

**Comment by Ike-Sanderson** [comment]
These are quite helpful- thank you!
